/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 banana.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/banana-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_35.geometry} material={materials.Banana_High} rotation={[-1.568, 0.264, 0.154]} />
    </group>
  )
}

useGLTF.preload('/banana-transformed.glb')
